version: "3.9"

services:
  strapi:
    build: .
    container_name: strapi-app
    env_file: .env
    ports:
      - "1337:1337"
    depends_on:
      - postgres
    networks:
      - strapi-net

  postgres:
    image: postgres:15
    container_name: strapi-db
    restart: always
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi-net

volumes:
  pgdata:

networks:
  strapi-net: